name: Security

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: '33 8 * * 1' # every Monday

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  trivy:
    runs-on: ubuntu-latest
    name: Trivy
    timeout-minutes: 10

    permissions:
      security-events: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        scan-type:
          - fs
          - config

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.19.0
        with:
          scan-type: ${{ matrix.scan-type }}
          scan-ref: .
          format: sarif
          output: trivy.json.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.json.sarif
